# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f12760e4e53122b826ffee502e6d4d7bc7d4d758398a9d454f490168991fb85983776ede29617d1252e860ee3b4e7256bad0c620da134ae1ea3b9aea802b8137

test:
  secret_key_base: 8dda7b613b7ad89bf70d62e8afb848c93c2e349b88ffaa8e88e1f1752c5a592d78cbeaa0898c37410cf50ed34cf130cf44763c4b6af99ab3de9b252f0d94fb07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
